module.exports.descriptors = [
    'Reindeer',
    'Norrsken',
    'Ice',
    'Aurora',
    'Hjortron',
    'Frost',
    'Brown Bear',
    'Polarnatt',
    'Arctic',
    'North Star',
    'Norra',
    'Snowy Peak',
    'Aurora Lake',
    'Polstjärnan',
    'Northern Light',
    'Polcirkeln',
    'Freezing',
    'Midvinter',
    'Midnight Sun',
    'Arctic Fox',
    'Golden Eagle',
    'Lynx',
    'Lingonris'
]

module.exports.places = [
    'Storstrand',
    'Vattendrag',
    'Camping',
    'Skärgård',
    'Vildmark',
    'Fjälltopp',
    'Camping & Resort',
    'Resort',
    'Familjecamping',
    'Skogstundra',
    'Friluftsområde',
    'Nationalpark',
    'Lagun',
    'Vattenfall',
    'Naturreservat',
    'Naturområde',
    'Reservat',
    'Naturpark',
    'Skogspark',
    'Skogscamping',
    'Kalfjäll',
    'Högfjäll'
]